name: Build and Release

env:
  REPO_URL: https://gitee.com/apaipai/dsm_helper.git
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: 0/30 * * * *

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11


    - name: Clone project
        # 拉取项目源码到虚拟环境
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH .\



    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
        
    - name: Execute Gradle build
      working-directory: .\android
      run: .\gradlew.bat

    - name: Upload APK
        # 打包上传生成的 APK 到的网页端
      uses: actions/upload-artifact@v2
      with:
        name: my-build-apk
        path: ./**/*.apk
